### ISSUE TITLE
Required BitArray

### ISSUE THREAD

**Issue by soccerno16** [GeezerGeek/open_sld#1]
Caveat:  This is the first time I've executed python.

You should make clear upfront that this script only works for Python 2.7

Your readme says that bitarray is required for the script to work.  In fact you should actually reference BITSTRING which uses "BitArray".
https://pypi.python.org/pypi/bitstring/3.1.3

Additionally, I had to add both the Quartus directory and open_sld-master to my path for the cmd session in order to get everything to work.

**Comment by GeezerGeek** [comment]
Thanks for the feedback. I updated the readme. I run the script with Python 2.6.
